name: GitHub Issue and Pagerduty Integration

on:
  issues:
    types: [opened, reopened]

jobs:
  create-pagerduty-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Send Alert Event
        uses: ACyphus/pagerduty-send-event@v1
        with:
          integration-key: ${{ secrets.PAGERDUTY_INTEGRATION_KEY }}
          event-action: trigger
          summary: '#${{ github.event.issue.number }} ${{ github.event.issue.title }}'
          source: 'GitHub Action in ${{ github.repository}}'
          severity: critical
          client: 'GCPM GitHub Issue Ticket'
          client-url: ${{ github.event.issue.html_url }}
