name: PagerDuty Alert Trigger

on:
  workflow_run:
    workflows: ["Pager Duty Test"]  # Replace with your workflow name
    types:
      - completed
  # Alternatively, trigger on push to main branch:
  # push:
  #   branches: [ main ]

jobs:
  send-pagerduty-alert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check workflow status
        id: check_status
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "::set-output name=status::failure"
            echo "::set-output name=message::Workflow ${{ github.event.workflow_run.name }} failed!"
          else
            echo "::set-output name=status::success"
          fi
      
      - name: Send event to PagerDuty (if failed)
        if: steps.check_status.outputs.status == 'failure'
        uses: ACyphus/pagerduty-send-event@v1
        with:
          integration-key: ${{ secrets.PAGERDUTY_INTEGRATION_KEY }}
          dedup-key: ${{ github.run_id }}
          event-action: trigger
          client: GitHub Actions
          client-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          severity: critical
          payload: |
            {
              "summary": "Workflow '${{ github.event.workflow_run.name }}' failed",
              "source": "GitHub Actions",
              "custom_details": {
                "workflow": "${{ github.event.workflow_run.name }}",
                "run_id": "${{ github.run_id }}",
                "repository": "${{ github.repository }}",
                "commit": "${{ github.sha }}",
                "failed_step": "See workflow logs",
                "run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            }
