name: GitHub Issue and Pagerduty Integration

on:
  issues:
    types: [opened, reopened]

env:
  ISSUE_URL: ${{ github.event.issue.html_url }}
  ISSUE_NUM: ${{ github.event.issue.number }}
  TITLE: ${{ github.event.issue.title }}
  REPO: ${{ github.repository}}

jobs:
  create-pagerduty-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Send Alert Event
        uses: ACyphus/pagerduty-send-event@v1
        with:
          integration-key: ${{ secrets.PAGERDUTY_INTEGRATION_KEY }}
          event-action: trigger
          summary: '#${{ env.ISSUE_NUM }} ${{ env.TITLE }}'
          source: 'GitHub Action in ${{ env.REPO }}'
          severity: critical
          client: '${{ env.REPO }} #${{ env.ISSUE_NUM }}'
          client-url: ${{ env.ISSUE_URL }}
